### PR TITLE
API Docs link is not to 404 page

### PR DESCRIPTION
**Pull request by iancoleman**
Change link from
404 http://docs.maidsafe.net/safe_core/master
to working link at
http://docs.maidsafe.net
although that link does not currently contain any docs for safe_core

### CODE REVIEW

**Comment by frabrunelle** [comment]
This link seems to work: http://docs.maidsafe.net/safe_client_libs/master/safe_core/index.html

**Comment by iancoleman** [comment]
Thanks for the correct link. The page at http://docs.maidsafe.net automatically redirects to the accumulator docs, when maybe it shouldn't.

**Comment by ustulation** [comment]
@frabrunelle do we still need this PR ?

**Comment by frabrunelle** [comment]
@ustulation: Maybe. The documentation link in the README (master branch) is still broken (https://docs.rs/safe_client_libs). Would it make sense to link to https://docs.rs/safe_core for now?

**Comment by Viv-Rajkumar** [comment]
@frabrunelle updated the badge links in master branch for crates.io and docs.rs https://github.com/maidsafe/safe_client_libs/commit/e1a0e8d639235294e8e383d7ff7d8be72affd6ad

**Comment by ustulation** [comment]
Changes incorporated

**Pull request closed without merging**
