### PR TITLE
chore/dependencies: cargo update -p rust_sodium

### PR DESCRIPTION
**Pull request by b-zee**
Updating `rust_sodium` results in an updated `openssl` crate which fixes a build error on some systems (e.g. Arch Linux). (See https://github.com/maidsafe/crust/issues/1012 and https://forum.safedev.org/t/safe-client-libs-compilation-problem-rust-openssl/2128)

I've run `cargo update -p rust_sodium` to update the `rust_sodium` dependencies. I've ran tests on both `safe_app` and `safe_core` in this way:

```
$ cargo test --release --features=use-mock-routing
```

Are there more things to test or take into account for this update?

### CODE REVIEW

**Comment by m-cat** [comment]
Thanks for the contribution! Unfortunately, it looks like the latest version of the `rand` crate fails to build on OSX. I'll report [an issue](https://github.com/rust-random/rand/issues) there.

> Are there more things to test or take into account for this update?

Yes, please see [the Testing section](https://github.com/maidsafe/safe_client_libs#testing) for information on running tests. Specifically, I would say this change warrants running tests for the real network in addition to the mock network, as a substantial number of dependencies have changed.

Thanks again 😄

**Comment by m-cat** [comment]
Running `cargo update` instead of just `cargo update -p rust_sodium` fixes the build failure on OSX. A likely cause is conflicting versions of dependencies (see [this issue](https://github.com/rust-random/rand/issues/695)) on OSX.

Pinging @nbaksalyar to make sure we want to update all of the dependencies at this time. Certainly we would want to run the entire test suite if so, including the binary compatibility tests.

**Comment by b-zee** [comment]
> Running `cargo update` instead of just `cargo update -p rust_sodium` fixes the build failure on OSX.

I ran `cargo update` and attempted the mock test with `cargo test --release --features=use-mock-routing`. I got the following error:

```
error[E0432]: unresolved import `crossbeam_utils::Backoff`
 --> /home/benno/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.3.7/src/context.rs:9:5
  |
9 | use crossbeam_utils::Backoff;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `Backoff` in the root

error[E0432]: unresolved import `crossbeam_utils::Backoff`
  --> /home/benno/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.3.7/src/flavors/array.rs:23:23
   |
23 | use crossbeam_utils::{Backoff, CachePadded};
   |                       ^^^^^^^ no `Backoff` in the root

error[E0432]: unresolved import `crossbeam_utils::Backoff`
  --> /home/benno/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.3.7/src/flavors/list.rs:10:23
   |
10 | use crossbeam_utils::{Backoff, CachePadded};
   |                       ^^^^^^^ no `Backoff` in the root

error[E0432]: unresolved import `crossbeam_utils::Backoff`
  --> /home/benno/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.3.7/src/flavors/zero.rs:10:5
   |
10 | use crossbeam_utils::Backoff;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `Backoff` in the root

error[E0432]: unresolved import `crossbeam_utils::Backoff`
 --> /home/benno/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.3.7/src/select.rs:8:5
  |
8 | use crossbeam_utils::Backoff;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `Backoff` in the root

error[E0432]: unresolved import `crossbeam_utils::Backoff`
  --> /home/benno/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.3.7/src/utils.rs:10:5
   |
10 | use crossbeam_utils::Backoff;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `Backoff` in the root
```

**Comment by b-zee** [comment]
Thanks for linking to that issue.

I tried `cargo update -p crossbeam-utils` as mentioned in that issue, but it didn't solve it. Then I tried updating manually to a precise version with `cargo update --package crossbeam-utils --precise 0.6.5`, yielding:

```
error: failed to select a version for `lazy_static`.
    ... required by package `crossbeam-utils v0.6.5`
    ... which is depended on by `tokio-timer v0.2.10`
    ... which is depended on by `tokio v0.1.15`
    ... which is depended on by `tokio-core v0.1.17`
    ... which is depended on by `safe_authenticator v0.9.0 (/home/benno/src/maidsafe/safe_client_libs/safe_authenticator)`
    ... which is depended on by `safe_app v0.9.0 (/home/benno/src/maidsafe/safe_client_libs/safe_app)`
    ... which is depended on by `tests v0.1.0 (/home/benno/src/maidsafe/safe_client_libs/tests)`
versions that meet the requirements `^1.1.0` are: 1.2.0, 1.1.0

all possible versions conflict with previously selected packages.

  previously selected package `lazy_static v1.0.2`
    ... which is depended on by `crossbeam-epoch v0.7.1`
    ... which is depended on by `crossbeam-deque v0.6.3`
    ... which is depended on by `tokio-threadpool v0.1.10`
    ... which is depended on by `tokio-fs v0.1.5`
    ... which is depended on by `tokio v0.1.15`
    ... which is depended on by `tokio-core v0.1.17`
    ... which is depended on by `safe_authenticator v0.9.0 (/home/benno/src/maidsafe/safe_client_libs/safe_authenticator)`
    ... which is depended on by `safe_app v0.9.0 (/home/benno/src/maidsafe/safe_client_libs/safe_app)`
    ... which is depended on by `tests v0.1.0 (/home/benno/src/maidsafe/safe_client_libs/tests)`

failed to select a version for `lazy_static` which could resolve this conflict
```

Updating `lazy_static` to either `1.2.0` with `cargo update --package lazy_static:1.0.2 --precise 1.2.0` yields:

```
error: failed to select a version for the requirement `lazy_static = "~1.0.0"`
  candidate versions found which didn't match: 1.2.0
  location searched: crates.io index
required by package `safe_core v0.32.0 (/home/benno/src/maidsafe/safe_client_libs/safe_core)`
```

So, that leads me to updating `lazy_static` to `~1.2.0` in `safe_core/Cargo.toml`.

After that, `cargo update` updates a few more packages and the tests run.

Running the test in `safe_app` gives me a weird error about 'too many open files'. Issuing `ulimit -n 70000` to raise the open files limit from 1024 on Linux fixes it (at least temporarily ?).

```
thread 'Alt client' panicked at '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   unwrap! called on Result::Err                                              !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
safe_core/src/utils/test_utils/mod.rs:123,14 in safe_core::utils::test_utils

Err(Os { code: 24, kind: Other, message: "Too many open files" })

', /home/benno/.cargo/registry/src/github.com-1ecc6299db9ec823/unwrap-1.2.1/src/lib.rs:67:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread panicked while panicking. aborting.
```

End result, `safe_app` and `safe_core` mock tests run fine. Anyhow, I committed the updated `safe_app/Cargo.toml` and `Cargo.lock` files to this pull request.

**Comment by b-zee** [comment]
Thought the CI test failing was incidental, so merged with master and committed to re-try the CI tests, but it results in the same error:

```
 Downloading rust_sodium v0.10.2
error: unable to get packages from source
Caused by:
  failed to parse manifest at `/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_sodium-0.10.2/Cargo.toml`
Caused by:
  editions are unstable
Caused by:
  feature `edition` is required
this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
```

Is this something I can fix, @m-cat ?

**Comment by m-cat** [comment]
That's caused by the latest version of `rust_sodium` already being at the 2018 Rust edition, and we have not yet moved Client Libs to 2018.

I believe @pierrechevalier83 began that process but ran into problems with `safe_bindgen`, if my memory serves correctly. Hopefully he can chime in on the status of that.

Thanks a lot for your patience @b-zee and your diligence in resolving these issues 👍

**Comment by nbaksalyar** [comment]
We fixed the aforementioned blockers and the PR #798 now should include all of these changes.
This PR can be closed now.

Thanks a lot for your help!

**Pull request closed without merging**
