### PR TITLE
Version change: safe_core to 0.37.0; safe_authenticator to 0.12.0; safe_app to 0.12.0

### PR DESCRIPTION
**Pull request by m-cat**

### CODE REVIEW

**Comment by m-cat** [comment]
Ah, I see. Yes, that sounds good to me @lionel1704

**Comment by lionel1704** [comment]
@m-cat the latest build on master has failed. We might need to fix that before merging this.

**Comment by m-cat** [comment]
Thanks for pointing that out, I raised a PR which should fix it. Running a test on my fork as well.

**Comment by m-cat** [comment]
Looks like it worked on my fork - my PR should be good to go.

**Pull request merged**
