### PR TITLE
Migrate to Rust 2018 + Allow usage as an external library

### PR DESCRIPTION
**Pull request by Thierry61**
This PR has 2 parts:

- First commit is to migrate safe_client_libs to Rust 2018. Modifications are essentially adding "crate::" in many use statements and removing some extern crate statements. Main difficulties are:
  - Adding an implementation of ReprC trait for UserPermissionSet type in safe_app/src/ffi/mutable_data/permissions.rs. I didn’t know what I was doing, I just wanted the code to compile, so this part is certainly wrong.
  - Replacing perm_set with ffi_perm_set in a test in safe_app/src/ffi/mutable_data/tests.rs (same here: the type was better matching for the compiler, but this is also certainly wrong)
  - Upgrading lazy_static version in safe_core/Cargo.toml (this one was found by @b-zee in another PR)

- Second commit is a one line modification to allow using this crate as an external lib: correction of error "cannot find macro `wait_for_response!` in this scope" mentioned in [this post](https://forum.safedev.org/t/trying-to-build-a-global-network/2266/3?u=tfa).

Remarks:
- The source repo has been modified in the interval, so I had to rebase my repo after my modifications. I hope this didn’t introduce any regressions.
- `cargo test` generates 18 passed and 43 failed because I haven't setup an external authenticator. The only test I did was testing the connection to an account on the community network (Authenticator::login)

### CODE REVIEW

**Comment by nbaksalyar** [comment]
Hello,

Thanks a lot for the PR! Continuous integration checks and tests will fail on this one for now because the [bindgen library](https://github.com/maidsafe/safe_bindgen) is incompatible with Rust 2018. We're on it, and it will be fixed soon. Then we'll be happy to merge these changes.

> Adding an implementation of ReprC trait for UserPermissionSet type

The implementation looks good :+1:  I'm just curious, in what context is it required? As far as I can see, it's not used in the FFI module?

> `cargo test` generates 18 passed and 43 failed because I haven't setup an external authenticator

You can test the library with the mock routing too. You can refer to [the documentation](https://github.com/maidsafe/safe_client_libs/wiki/Testing-Client-Libs#mock-routing) to learn more about this.

**Comment by Thierry61** [comment]
>in what context is it required? As far as I can see, it's not used in the FFI module?

I added this trait implementation to correct following error with `cargo test` command:

```
error[E0277]: the trait bound `ffi::mutable_data::permissions::UserPermissionSet: ffi_utils::ReprC` is not satisfied
  --> safe_app/src/ffi/mutable_data/tests.rs:80:21
   |
80 |             unwrap!(call_vec(|ud, cb| mdata_list_permission_sets(
   |                     ^^^^^^^^ the trait `ffi_utils::ReprC` is not implemented for `ffi::mutable_data::permissions::UserPermissionSet`
   |
   = note: required by `ffi_utils::test_utils::call_vec`
```

**Comment by nbaksalyar** [comment]
@Thierry61 
> I added this trait implementation to correct following error <...>

The cause of that error is this dependency:
https://github.com/maidsafe/safe_client_libs/blob/845be0bc660620416a0ce37e40268b027a321e36/safe_app/src/ffi/mutable_data/tests.rs#L21

with Rust 2018 it translates into a fully-qualified path like `safe_app::ffi::mutable_data::permissions::UserPermissionSet` while without the `edition = "2018"` it's `safe_app::permissions::UserPermissionSet`.

So it should be changed to
> use crate::permissions::UserPermissionSet;

and then we wouldn't need that extra `ReprC` thing :slightly_smiling_face: 

I've made this change and it works like a charm. I've also updated the code to build with `--features use-mock-routing`. I'll submit a new pull request based on this one.

And thanks again for your help!

**Comment by Thierry61** [comment]
Thanks @nbaksalyar. As you are taking care of this, I am closing my PR.

**Pull request closed without merging**
